'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="SAFETY")>  _
Partial Public Class DataPermitDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertSAFETY_AREA(instance As SAFETY_AREA)
    End Sub
  Partial Private Sub UpdateSAFETY_AREA(instance As SAFETY_AREA)
    End Sub
  Partial Private Sub DeleteSAFETY_AREA(instance As SAFETY_AREA)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("SAFETYConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property SAFETY_AREAs() As System.Data.Linq.Table(Of SAFETY_AREA)
		Get
			Return Me.GetTable(Of SAFETY_AREA)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.SAFETY_AREA")>  _
Partial Public Class SAFETY_AREA
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _AREANO As Integer
	
	Private _AREADIV As String
	
	Private _AREADEP As String
	
	Private _AREAEMPCODE As String
	
	Private _AREAEMPNAME As String
	
	Private _AREAEMAIL As String
	
	Private _AREADATAIL As String
	
	Private _AREACREATEDATE As System.Nullable(Of Date)
	
	Private _AREACHECKNO As System.Nullable(Of Integer)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAREANOChanging(value As Integer)
    End Sub
    Partial Private Sub OnAREANOChanged()
    End Sub
    Partial Private Sub OnAREADIVChanging(value As String)
    End Sub
    Partial Private Sub OnAREADIVChanged()
    End Sub
    Partial Private Sub OnAREADEPChanging(value As String)
    End Sub
    Partial Private Sub OnAREADEPChanged()
    End Sub
    Partial Private Sub OnAREAEMPCODEChanging(value As String)
    End Sub
    Partial Private Sub OnAREAEMPCODEChanged()
    End Sub
    Partial Private Sub OnAREAEMPNAMEChanging(value As String)
    End Sub
    Partial Private Sub OnAREAEMPNAMEChanged()
    End Sub
    Partial Private Sub OnAREAEMAILChanging(value As String)
    End Sub
    Partial Private Sub OnAREAEMAILChanged()
    End Sub
    Partial Private Sub OnAREADATAILChanging(value As String)
    End Sub
    Partial Private Sub OnAREADATAILChanged()
    End Sub
    Partial Private Sub OnAREACREATEDATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnAREACREATEDATEChanged()
    End Sub
    Partial Private Sub OnAREACHECKNOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnAREACHECKNOChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREANO", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property AREANO() As Integer
		Get
			Return Me._AREANO
		End Get
		Set
			If ((Me._AREANO = value)  _
						= false) Then
				Me.OnAREANOChanging(value)
				Me.SendPropertyChanging
				Me._AREANO = value
				Me.SendPropertyChanged("AREANO")
				Me.OnAREANOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREADIV", DbType:="VarChar(100)")>  _
	Public Property AREADIV() As String
		Get
			Return Me._AREADIV
		End Get
		Set
			If (String.Equals(Me._AREADIV, value) = false) Then
				Me.OnAREADIVChanging(value)
				Me.SendPropertyChanging
				Me._AREADIV = value
				Me.SendPropertyChanged("AREADIV")
				Me.OnAREADIVChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREADEP", DbType:="VarChar(100)")>  _
	Public Property AREADEP() As String
		Get
			Return Me._AREADEP
		End Get
		Set
			If (String.Equals(Me._AREADEP, value) = false) Then
				Me.OnAREADEPChanging(value)
				Me.SendPropertyChanging
				Me._AREADEP = value
				Me.SendPropertyChanged("AREADEP")
				Me.OnAREADEPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREAEMPCODE", DbType:="Char(10)")>  _
	Public Property AREAEMPCODE() As String
		Get
			Return Me._AREAEMPCODE
		End Get
		Set
			If (String.Equals(Me._AREAEMPCODE, value) = false) Then
				Me.OnAREAEMPCODEChanging(value)
				Me.SendPropertyChanging
				Me._AREAEMPCODE = value
				Me.SendPropertyChanged("AREAEMPCODE")
				Me.OnAREAEMPCODEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREAEMPNAME", DbType:="VarChar(100)")>  _
	Public Property AREAEMPNAME() As String
		Get
			Return Me._AREAEMPNAME
		End Get
		Set
			If (String.Equals(Me._AREAEMPNAME, value) = false) Then
				Me.OnAREAEMPNAMEChanging(value)
				Me.SendPropertyChanging
				Me._AREAEMPNAME = value
				Me.SendPropertyChanged("AREAEMPNAME")
				Me.OnAREAEMPNAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREAEMAIL", DbType:="VarChar(100)")>  _
	Public Property AREAEMAIL() As String
		Get
			Return Me._AREAEMAIL
		End Get
		Set
			If (String.Equals(Me._AREAEMAIL, value) = false) Then
				Me.OnAREAEMAILChanging(value)
				Me.SendPropertyChanging
				Me._AREAEMAIL = value
				Me.SendPropertyChanged("AREAEMAIL")
				Me.OnAREAEMAILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREADATAIL", DbType:="VarChar(250)")>  _
	Public Property AREADATAIL() As String
		Get
			Return Me._AREADATAIL
		End Get
		Set
			If (String.Equals(Me._AREADATAIL, value) = false) Then
				Me.OnAREADATAILChanging(value)
				Me.SendPropertyChanging
				Me._AREADATAIL = value
				Me.SendPropertyChanged("AREADATAIL")
				Me.OnAREADATAILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREACREATEDATE", DbType:="DateTime")>  _
	Public Property AREACREATEDATE() As System.Nullable(Of Date)
		Get
			Return Me._AREACREATEDATE
		End Get
		Set
			If (Me._AREACREATEDATE.Equals(value) = false) Then
				Me.OnAREACREATEDATEChanging(value)
				Me.SendPropertyChanging
				Me._AREACREATEDATE = value
				Me.SendPropertyChanged("AREACREATEDATE")
				Me.OnAREACREATEDATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AREACHECKNO", DbType:="Int")>  _
	Public Property AREACHECKNO() As System.Nullable(Of Integer)
		Get
			Return Me._AREACHECKNO
		End Get
		Set
			If (Me._AREACHECKNO.Equals(value) = false) Then
				Me.OnAREACHECKNOChanging(value)
				Me.SendPropertyChanging
				Me._AREACHECKNO = value
				Me.SendPropertyChanged("AREACHECKNO")
				Me.OnAREACHECKNOChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
